### BGP ###
bgp_peer_groups:
  ipv4_underlay_peers:
    password: "OrD4gpT3JYQrZR7rYGfBbP0zCFZd5CTQPPvlhBHKwwI="
    bfd: false
    structured_config:
      route_reflector_client: true
      next_hop_self: true
  evpn_overlay_peers:
    password: "hCAawBQGfCnaIbhPRT8jl4ounMM+V8Kf"
    bfd: false
    structured_config:
      remote_as: 65561