all:
  children:
    acme_fabric:
      children:
        dc01:
          children:
            dc01_fw:
              hosts:
                dc01-fw01: null
                dc01-fw02: null
              vars:
                type: firewall
            dc01_leaf:
              hosts:
                dc01-gw01a: null
                dc01-gw01b: null
                dc01-le01a: null
                dc01-le01b: null
                dc01-le02a: null
                dc01-le02b: null
                dc01-le03a: null
                dc01-le03b: null
                dc01-srv01a: null
                dc01-srv01b: null
              vars:
                type: l3leaf
            dc01_spine:
              hosts:
                dc01-sp01: null
                dc01-sp02: null
              vars:
                type: spine
        dc02:
          children:
            dc02_fw:
              hosts:
                dc02-fw01: null
                dc02-fw02: null
              vars:
                type: firewall
            dc02_leaf:
              hosts:
                dc02-gw01a: null
                dc02-gw01b: null
                dc02-le01a: null
                dc02-le01b: null
                dc02-le02a: null
                dc02-le02b: null
                dc02-srv01a: null
                dc02-srv01b: null
              vars:
                type: l3leaf
            dc02_spine:
              hosts:
                dc02-sp01: null
                dc02-sp02: null
              vars:
                type: spine
        servers:
          hosts:
            server01:
              vars:
                srv_gw: 10.4.40.1
                srv_ip: 10.4.40.101
            server02:
              vars:
                srv_gw: 10.4.41.1
                srv_ip: 10.4.41.102
            server03:
              vars:
                srv_gw: 10.4.45.1
                srv_ip: 10.4.45.103
            server04:
              vars:
                srv_gw: 10.4.41.1
                srv_ip: 10.4.41.104
            server07:
              vars:
                srv_gw: 10.4.44.1
                srv_ip: 10.4.44.107
            server08:
              vars:
                srv_gw: 10.5.55.1
                srv_ip: 10.5.55.108
            server09:
              vars:
                srv_gw: 10.4.44.1
                srv_ip: 10.4.44.109
            server10:
              vars:
                srv_gw: 10.5.50.1
                srv_ip: 10.5.50.110
            server11:
              vars:
                srv_gw: 10.4.40.1
                srv_ip: 10.4.40.111
            server13:
              vars:
                srv_gw: 10.5.51.1
                srv_ip: 10.5.51.113
            server14:
              vars:
                srv_gw: 10.5.54.1
                srv_ip: 10.5.54.114
            server15:
              vars:
                srv_gw: 10.5.51.1
                srv_ip: 10.5.51.115
            server16:
              vars:
                srv_gw: 10.5.54.1
                srv_ip: 10.5.54.116
            server17:
              vars:
                srv_gw: 10.4.45.1
                srv_ip: 10.4.45.117
            server18:
              vars:
                srv_gw: 10.4.43.1
                srv_ip: 10.4.43.118
            server19:
              vars:
                srv_gw: 10.4.42.1
                srv_ip: 10.4.42.119
            server20:
              vars:
                srv_gw: 10.4.49.1
                srv_ip: 10.4.49.120
            server22:
              vars:
                srv_gw: 10.4.44.1
                srv_ip: 10.4.44.122
            server23:
              vars:
                srv_gw: 10.5.52.1
                srv_ip: 10.5.52.123
            server24:
              vars:
                srv_gw: 10.4.44.1
                srv_ip: 10.4.44.124
            server25:
              vars:
                srv_gw: 10.5.52.1
                srv_ip: 10.5.52.125
            server27:
              vars:
                srv_gw: 10.5.53.1
                srv_ip: 10.5.53.127
            server28:
              vars:
                srv_gw: 10.5.55.1
                srv_ip: 10.5.55.128
            server29:
              vars:
                srv_gw: 10.5.53.1
                srv_ip: 10.5.53.129
            server30:
              vars:
                srv_gw: 10.5.54.1
                srv_ip: 10.5.54.130
          vars:
            type: server
      vars:
        ansible_become: true
        ansible_become_method: enable
        ansible_connection: httpapi
        ansible_httpapi_use_ssl: true
        ansible_httpapi_validate_certs: false
        ansible_network_os: eos
        ansible_ssh_pass: arista1234
        ansible_user: cvpadmin
    cvp:
      hosts:
        cv_server:
          ansible_connection: httpapi
          ansible_host: 10.18.162.176
          ansible_httpapi_host: 10.18.162.176
          ansible_httpapi_port: 443
          ansible_httpapi_use_ssl: true
          ansible_httpapi_validate_certs: false
          ansible_network_os: eos
          ansible_password: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjczNzUwMzM4MjMwOTM4NTAzMjksImRzbiI6ImN2cCIsImRzdCI6ImFjY291bnQiLCJleHAiOjE3NDYwODY0NjcsImlhdCI6MTcxNzE0MjQ3OCwib2dpIjozLCJvZ24iOiJEZWZhdWx0Iiwic2lkIjoiNTdmODEyNzkzYzczMjE3ODdkNTA5MDAyN2M5OTZmMzQxY2RhNDhkMTBlYTJiMTI0ZTM5YTEzN2E1ODI4ZTIwMy1ZdGFvMHVMTmVfVDY5bm5DRG03Rmg2S1pIOEVlQ0lvbGt2dWdRQWhBIn0.eYgktuDRZiznE6je34RiXR7vGwZUlOGmiV75qfXTriTLROp1L0ZkFE9A3ipcPEh35IEOy_1Fbhp_527VYhVYvNHtsfL0uU2n6zxqQ6GySE_v7w0RsAnpniuPcxf1iGHG-Ky7tuKiPifrgaR5wpgERHh4TYjubRw2B33iYblQkBEC8s_94IuUw-SXJ2p2NDrWMnKJyuRCoe9GRIqps3nlSIiqcObow2qWp-qY3d6oGB3ulwMslDxKZ4lU3mqaKXYwogXW4QcjNkfGWODIW68TSdYD12G2k4ma9zn7RaM9yyirEPP9jbXki5L6OsxKvfkGefGAs9lyj3l3j_5u7-gSPkTgsbn1RKh5gD789oco8XzvYDjxJr1dNt00_926JYX-KGFyR-tVerG9j3ciXetvpdP5kKEyp9kb9H68gd2Kgzu3m1QX01dMAlePIv1yuKJA6_7MbnQCDNvNSMt6RPrLdadtbSm5IqlvcEymLC6kFdDDCWfKN7VDQ6QAbl0eaYgDTdzkgo6yhghgaypRmaDZ38r0awaVVaWJ20lEwB6iaMkEVITz7aX0KPWb3Onw-zNDo2mCF09dtInFxG70PQcUMj1yf4GTh3-1g2si23l1nnFRaXz1amUqvUMT0b4ApHkGLpcyd9N6Qb9vlJRXyird1orsIEuLN3zjR6dPqLipY_A
          ansible_user: svc_account
        cv_ztp:
          ansible_host: 10.255.123.151
          ansible_password: cvproot
          ansible_user: root
    dc01_compute:
      children:
        dc01_leaf: null
    dc02_compute:
      children:
        dc02_leaf: null
    dc_leaf:
      children:
        dc01_leaf: null
        dc02_leaf: null
    dc_service:
      hosts:
        dc01-srv01a: null
        dc01-srv01b: null
        dc02-srv01a: null
        dc02-srv01b: null
    dc_spine:
      children:
        dc01_spine: null
        dc02_spine: null
    switches:
      children:
        dc01: null
        dc02: null
  vars:
    ansible_python_interpreter: python3
