### GENERAL
is_deployed: true

### PORT-CHANNELS
port_channel_interfaces:
  - name: Port-channel1
    description: LINK_TO_DC01_SRV01
    shutdown: false
    mode: trunk
    vlans: 41,45,51,55,200-203
    type: switched

### ETHERNET INTERFACES
ethernet_interfaces:
  - name: Ethernet1
    description: LINK_TO_DC01_SRV01A_27
    shutdown: false
    mode: trunk
    vlans: 41,45,51,55,200-203
    type: port-channel-member
    channel_group:
      id: 1
      mode: active
  - name: Ethernet2
    description: LINK_TO_DC01_SRV01B_27
    shutdown: false
    mode: trunk
    vlans: 41,51,200-203
    type: port-channel-member
    channel_group:
      id: 1
      mode: active

### NETWORK SERVICES
tenants:
  - name: acme
    vrfs:
      - name: ACME-GENERAL
        svis:
          - id: 41
            name: ACME_GENERAL_41
            enabled: true
            ip_address: 10.4.41.1/24
          - id: 200
            name: TRANSIT_TO_ACME_GENERAL
            enabled: true
            ip_address: 10.0.0.62/29
        static_routes:
          - destination_address_prefix: 0.0.0.0/0
            gateway: 10.0.0.57
            name: ACME-GENERAL-PROTECTED-VLANS
      - name: ACME-DT
        svis:
          - id: 51
            name: ACME_DT_51
            enabled: true
            ip_address: 10.5.51.1/24
          - id: 201
            name: TRANSIT_TO_ACME_DT
            enabled: true
            ip_address: 10.0.0.78/29
        static_routes:
          - destination_address_prefix: 0.0.0.0/0
            gateway: 10.0.0.73
            name: ACME-DT-PROTECTED-VLANS
      - name: ACME-FUSION
        svis:
          - id: 202
            name: FUSION_ACME_GENERAL_TO_ACME_DT
            enabled: true
            ip_address: 10.0.0.70/29
          - id: 203
            name: FUSION_ACME_DT_TO_ACME_GENERAL
            enabled: true
            ip_address: 10.0.0.86/29
        static_routes:
          - destination_address_prefix: 10.4.0.0/16
            gateway: 10.0.0.65
            name: ACME-FUSION-GENERAL-TO-DT
          - destination_address_prefix: 10.5.0.0/16
            gateway: 10.0.0.81
            name: ACME-FUSION-GENERAL-TO-DT