### GENERAL
is_deployed: true

### PORT-CHANNELS
port_channel_interfaces:
  - name: Port-channel1
    description: LINK_TO_DC02_SRV01
    shutdown: false
    mode: trunk
    vlans: 43,53,204-207
    type: switched

### ETHERNET INTERFACES
ethernet_interfaces:
  - name: Ethernet1
    description: LINK_TO_DC02_SRV01A_27
    shutdown: false
    mode: trunk
    vlans: 43,53,204-207
    type: port-channel-member
    channel_group:
      id: 1
      mode: active
  - name: Ethernet2
    description: LINK_TO_DC02_SRV01B_27
    shutdown: false
    mode: trunk
    vlans: 443,53,204-207
    type: port-channel-member
    channel_group:
      id: 1
      mode: active

### NETWORK SERVICES
tenants:
  - name: acme
    vrfs:
      - name: ACME-GENERAL
        svis:
          - id: 43
            name: ACME_GENERAL_43
            enabled: true
            ip_address: 10.4.43.1/24
          - id: 204
            name: TRANSIT_TO_ACME_GENERAL
            enabled: true
            ip_address: 10.0.0.94/29
        static_routes:
          - destination_address_prefix: 0.0.0.0/0
            gateway: 10.0.0.89
            name: ACME-GENERAL-PROTECTED-VLANS
      - name: ACME-DT
        svis:
          - id: 53
            name: ACME_DT_53
            enabled: true
            ip_address: 10.5.53.1/24
          - id: 205
            name: TRANSIT_TO_ACME_DT
            enabled: true
            ip_address: 10.0.0.110/29
        static_routes:
          - destination_address_prefix: 0.0.0.0/0
            gateway: 10.0.0.105
            name: ACME-DT-PROTECTED-VLANS
      - name: ACME-FUSION
        svis:
          - id: 206
            name: FUSION_ACME_GENERAL_TO_ACME_DT
            enabled: true
            ip_address: 10.0.0.102/29
          - id: 207
            name: FUSION_ACME_DT_TO_ACME_GENERAL
            enabled: true
            ip_address: 10.0.0.118/29
        static_routes:
          - destination_address_prefix: 10.4.0.0/16
            gateway: 10.0.0.97
            name: ACME-FUSION-GENERAL-TO-DT
          - destination_address_prefix: 10.5.0.0/16
            gateway: 10.0.0.113
            name: ACME-FUSION-GENERAL-TO-DT